### PR TITLE
Fix undeclared variables and inconsistent assignments, continued

### PR DESCRIPTION
**Pull request by muzimuzhi**
See #22.

BREAKING CHANGE: Using an undefined template in `\SetTblrTemplate` now raises an error.

Deprecated `\tl_case:N(TF)` is not replaced with `\token_case_meaning:N(TF)` as the former was deprecated on 2022-05-23, relatively recently.

### CODE REVIEW

**Comment by lvjr** [comment]
In `table-001.tlg`, `tabularray` version number is removed but `varwidth` version number remains. Maybe it is a bug of `l3build`.

**Comment by muzimuzhi** [comment]
This PR supersedes #483, except for the `\tl_case:N(TF)` to `\token_case_meaning:N(TF)` replacement.

**Comment by muzimuzhi** [comment]
> In `table-001.tlg`, `tabularray` version number is removed but `varwidth` version number remains. Maybe it is a bug of `l3build`.

`varwidth` uses a non-conventional version notation ("ver 0.92") while `l3build` only replaces the `v<version>` pattern. I've ignored log lines produced when loading `varwidth` package.

```
Package: tabularray ....-..-.. v... Typeset tabulars and arrays with LaTeX3
Package: varwidth ....-..-.. ver 0.92;  Variable-width minipages
```

**Comment by lvjr** [comment]
> Deprecated `\tl_case:N(TF)` is not replaced with `\token_case_meaning:N(TF)` as the former was deprecated on 2022-05-23, relatively recently.

This reminds me that it is needed to add something to doc about how many texlive releases are supported by `tabularray`.

**Comment by lvjr** [comment]
Maybe we can support four texlive releases (with all updates). For example, `tabularray` releases published in 2025 could be used in texlive 2022-2025 with latest updates.

**Pull request merged**
