### PR TITLE
Two small improvements for named indexes U-Z

### PR DESCRIPTION
**Pull request by muzimuzhi**
Currently,
- Named indexes U-Z are supported in both from- and to-part of simple selectors like `cell{-}{U-Z}={preto=x}`, but only in to-part of child selectors `odd/even`. Thus `cell{-}{even[2-Z]}={preto=x}` is supported but `cell{-}{even[X-Z]}={preto=x}` is not.
- The indexes converted from U-Z may be non-positive (hence invalid for following processes) in tables with small number of columns or rows.

This PR adds support for from-part of `odd/even` selectors and ensures the converted indexes are at least 1.

### CODE REVIEW

**Comment by lvjr** [comment]
I think it will bring more and more troubles if a package starts to correct wrong user inputs: to me `X` is a wrong input if a table has only two rows and should cause errors.

**Comment by lvjr** [comment]
@muzimuzhi Could you help to confirm that l3build doesn't normalize end-of-line characters in `.tlg` files? It seems the eol characters are different on macos/linux.

**Comment by muzimuzhi** [comment]
> I think it will bring more and more troubles if a package starts to correct wrong user inputs: to me `X` is a wrong input if a table has only two rows and should cause errors.

It depends on how intelligent the language/package want to be.  Named indexes U-Z are already part of that intelligence, and child selectors a family of another.  For example `python`'s [slicing](https://docs.python.org/3/library/stdtypes.html#sequence-types-list-tuple-range) supports
```python
>>> a = [1,2,3]
>>> a[-10:-1]
[1, 2]
>>> a[-10:10]
[1, 2, 3]
```
Currently
```tex
\documentclass{article}
\usepackage{tabularray}

\begin{document}
% `cell{-}{Y-Z}` works
\begin{tblr}{
  hlines, vlines,
  cell{-}{1-X}={preto=x}
}
  & & & \\
\end{tblr}

% `cell{-}{U-Z}` explodes
\begin{tblr}{
  hlines, vlines,
  % U = -6, Z = -1, four-column table
  cell{-}{U-X}={preto=x}
}
  & & & \\
\end{tblr}
\end{document}
```
throws low level error and the non-positive index is treated as zero.
```
! Missing number, treated as zero.
<to be read again> 
                   ;
l.20 \end
         {tblr}
```
Thus I suggest to give a more helpful error message and (still) use 1 as fallback value.

**Comment by muzimuzhi** [comment]
> Could you help to confirm that l3build doesn't normalize end-of-line characters in `.tlg` files? It seems the eol characters are different on macos/linux.

`l3build` won't normalize EOL.  The `.tlg` is generated on macOS and checked by the GitHub Actions workflow on Ubuntu and Windows.  What's the concrete problem/difference you noticed?

**Comment by lvjr** [comment]
> `l3build` won't normalize EOL. The `.tlg` is generated on macOS and checked by the GitHub Actions workflow on Ubuntu and Windows. What's the concrete problem/difference you noticed?
> 
See `extra-002.tlg` file in this pull request. It is quite annoying that the diff of this file is wrong.

**Comment by muzimuzhi** [comment]
> > `l3build` won't normalize EOL. The `.tlg` is generated on macOS and checked by the GitHub Actions workflow on Ubuntu and Windows. What's the concrete problem/difference you noticed?
> 
> See `extra-002.tlg` file in this pull request. It is quite annoying that the diff of this file is wrong.

It's OS specific. Windows uses CRLF while *-nix tends to use LF, see https://www.wikiwand.com/en/Newline#Representation. As I appended to https://github.com/lvjr/tabularray/pull/385#issuecomment-1474851896, 

> Just guessing, `git` configs [`core.eol`](https://git-scm.com/docs/git-config#Documentation/git-config.txt-coreeol) and [`core.autocrlf`](https://git-scm.com/docs/git-config#Documentation/git-config.txt-coreautocrlf) may help.

and GitHub also provides [a setting to hide whitespace](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/about-comparing-branches-in-pull-requests#diff-view-options) when reviewing.

I will try with git configs and perhaps push a commit to use CRLF.

**Comment by lvjr** [comment]
>Just guessing, git configs [core.eol](https://git-scm.com/docs/git-config#Documentation/git-config.txt-coreeol) and [core.autocrlf](https://git-scm.com/docs/git-config#Documentation/git-config.txt-coreautocrlf) may help.

I always turn off this `autocrlf` option in my local git repos, because I believe git should not touch these kind of things. It is a job of repo maintainers and build tools to decide and normalize eol characters.

But l3build is missing this feature. Maybe someday I will add some code to `build.lua` to normalize eol characters of `tlg` files. It seems doable.

**Comment by lvjr** [comment]
>Just guessing, git configs [core.eol](https://git-scm.com/docs/git-config#Documentation/git-config.txt-coreeol) and [core.autocrlf](https://git-scm.com/docs/git-config#Documentation/git-config.txt-coreautocrlf) may help.

I always turn off this `autocrlf` option in my local git repos, because I believe git should not touch these kind of things. It is a job of repo maintainers and build tools to decide and normalize eol characters.

But l3build is missing this feature. Maybe someday I will add some code to `build.lua` to normalize eol characters of `tlg` files. It seems doable.

**Comment by davidcarlisle** [comment]
you could open an issue at L3build

**Comment by muzimuzhi** [comment]
> `l3build` won't normalize EOL.

I was wrong by using wrong patterns `%r`/`%n` yesterday.  An issue is opened at l3build, https://github.com/latex3/l3build/issues/293.

**Comment by muzimuzhi** [comment]
> > Just guessing, git configs [core.eol](https://git-scm.com/docs/git-config#Documentation/git-config.txt-coreeol) and [core.autocrlf](https://git-scm.com/docs/git-config#Documentation/git-config.txt-coreautocrlf) may help.
> 
> I always turn off this `autocrlf` option in my local git repos, because I believe git should not touch these kind of things. It is a job of repo maintainers and build tools to decide and normalize eol characters.

Seems it's not always like this, for example front-end tools `babel` and `npm` both don't normalize EOL, see https://github.com/latex3/l3build/issues/293#issuecomment-1480586715.

EOL are special characters that are (almost) transparent to human and most modern programs that read in files, and perhaps only meaningful for softwares that compute file checksums or do file comparisons.  So it's not too bad for git to touch EOLs.

**Comment by muzimuzhi** [comment]
`l3build` doesn't normalize EOL when saving, but does normalize EOLs [when checking](https://github.com/latex3/l3build/blob/f75745818250cc873638af4f7c2506c171a2cc41/l3build-check.lua#L98). As a proof, the `CTeX-org/ctex-kit` run tests on all three OS, using the same set of `.tlg` (example [passed run](https://github.com/CTeX-org/ctex-kit/actions/runs/11629223062)).

Either I didn't know the full story or I expressed it ambiguously when composing https://github.com/lvjr/tabularray/pull/385#issuecomment-1474851896.

**Comment by lvjr** [comment]
@muzimuzhi With `*.tlg text eol=lf` eol characters in `hvline-004.tlg` are different from those in other `tlg` files in my Windows computer. Do you think it is a good idea to change it to `*.tlg text eol=auto`? I guess it will not affect files in GitHub repository?

**Comment by muzimuzhi** [comment]
I have no idea...

**Comment by lvjr** [comment]
I have changed it to `*.tlg text !eol` after some tests on pull and push actions, Now EOL characters are always CRLF in my Windows computer and always LF in GitHub repository.

**Pull request merged**
